# The comments in this file show via example how to override some of the most popular set of options.
# However, it is possible to override any Docker configuration setting, for example Port mappings, by adding the override here.
version: '3.6'
#services:
  #postgres:
    #deploy:
    ## This placement constraint example requires running:  docker node update --label-add type=db xxxNodeId
    ## Note: postgres and postgres-upgrader must be deployed to the name node
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #postgres-upgrader:
    #deploy:
    ## This placement constraint example requires running:  docker node update --label-add type=db xxxNodeId
    ## Note: postgres and postgres-upgrader must be deployed to the name node
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #authentication:
    #secrets:
    #  - HUB_SERVICE_GENAI_OLD_PASSWORD_FILE
    #  - HUB_SERVICE_GENAI_CURRENT_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
  #webapp:
    #environment:
    #  HUB_MAX_MEMORY: REPLACE_WITH_NEW_HUB_MAX_HEAP_MEMORYm
    #  HUB_MIN_MEMORY: REPLACE_WITH_NEW_HUB_MIN_HEAP_MEMORYm
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #scan:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS
  #storage:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #jobrunner:
    #environment:
    #  HUB_MAX_MEMORY: REPLACE_WITH_NEW_HUB_MAX_HEAP_MEMORYm
    #  HUB_MIN_MEMORY: REPLACE_WITH_NEW_HUB_MIN_HEAP_MEMORYm
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS
  #logstash:
    #environment:
    #  HUB_MAX_MEMORY: REPLACE_WITH_NEW_HUB_MAX_HEAP_MEMORYm
    #  HUB_MIN_MEMORY: REPLACE_WITH_NEW_HUB_MIN_HEAP_MEMORYm
    #deploy:
    #  placement:
    #    constraints:
    #    - node.labels.type == db
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
  #registration:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #deploy:
    #  placement:
    #    constraints:
    #    - node.labels.type == db
  #webserver:
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - WEBSERVER_CUSTOM_CERT_FILE
    #  - WEBSERVER_CUSTOM_KEY_FILE
  #bomengine:
    #environment:
    #  HUB_MAX_MEMORY: REPLACE_WITH_NEW_HUB_MAX_HEAP_MEMORYm
    #  HUB_MIN_MEMORY: REPLACE_WITH_NEW_HUB_MIN_HEAP_MEMORYm
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS
  #matchengine:
    #environment:
    #  HUB_MAX_MEMORY: REPLACE_WITH_NEW_HUB_MAX_HEAP_MEMORYm
    #  HUB_MIN_MEMORY: REPLACE_WITH_NEW_HUB_MIN_HEAP_MEMORYm
    #secrets:
    #  - HUB_PROXY_PASSWORD_FILE
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
    #deploy:
    #  resources:
    #    limits: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #    reservations: {cpus: 'REPLACE_WITH_NUM_CPUS', memory: REPLACE_WITH_NEW_MEM_LIMITm}
    #  replicas: REPLACE_WITH_NUM_REPLICAS
  #integration:
    #secrets:
    #  - JWT_PUBLIC_KEY
    #  - JWT_PRIVATE_KEY
#secrets:
#  HUB_PROXY_PASSWORD_FILE:
#    external: true
#    name: "hub_PROXY_PASSWORD_FILE"
#  WEBSERVER_CUSTOM_CERT_FILE:
#    external: true
#    name: "hub_WEBSERVER_CUSTOM_CERT_FILE"
#  WEBSERVER_CUSTOM_KEY_FILE:
#    external: true
#    name: "hub_WEBSERVER_CUSTOM_KEY_FILE"
#  HUB_SERVICE_GENAI_OLD_PASSWORD_FILE:
#    external: true
#    name: "hub_SERVICE_GENAI_OLD_PASSWORD_FILE"
#  HUB_SERVICE_GENAI_CURRENT_PASSWORD_FILE:
#    external: true
#    name: "hub_SERVICE_GENAI_CURRENT_PASSWORD_FILE"
#  JWT_PUBLIC_KEY:
#    external: true
#    name: "hub_JWT_PUBLIC_KEY"
#  JWT_PRIVATE_KEY:
#    external: true
#    name: "hub_JWT_PRIVATE_KEY"
