apiVersion: v1
data:
  {{- include "bd.defaultNonConfigurableEnvirons" . | nindent 2 }}
  {{- include "bd.postgresConnectionAdmin" . | nindent 2 }}
  {{- include "bd.postgresConnectionUser" . | nindent 2 }}
  {{- include "bd.postgresql.internal.vs.external" . | nindent 2 }}
  {{- include "bd.environs" . | nindent 2 }}
  {{- include "enableSourceCodeUpload" . | nindent 2 }}
  {{- include "enableBinaryScanner" . | nindent 2 }}
  {{- include "enableIntegration" . | nindent 2 }}
  {{- include "enableIPV6" . | nindent 2 }}
  {{- include "enableAlert" . | nindent 2 }}
  {{- include "customNodePort" . | nindent 2 }}
  {{- include "customRedis" . | nindent 2 }}
  {{- if .Values.jobrunner.maxPeriodicThreads }}
  org.quartz.scheduler.periodic.maxthreads: "{{ .Values.jobrunner.maxPeriodicThreads }}"
  {{- end}}
  {{- if .Values.jobrunner.maxPeriodicPrefetch }}
  org.quartz.scheduler.periodic.prefetch: "{{ .Values.jobrunner.maxPeriodicPrefetch }}"
  {{- end}}
  {{- if .Values.jobrunner.maxOndemandThreads }}
  org.quartz.scheduler.ondemand.maxthreads: "{{ .Values.jobrunner.maxOndemandThreads }}"
  {{- end}}
  {{- if .Values.jobrunner.maxOndemandPrefetch }}
  org.quartz.scheduler.ondemand.prefetch: "{{ .Values.jobrunner.maxOndemandPrefetch }}"
  {{- end}}
  {{- if .Values.webserver.webserverWorkerProcesses }}
  WEBSERVER_WORKER_PROCESSES: "{{ .Values.webserver.webserverWorkerProcesses }}"
  {{- end}}
  {{- if .Values.webserver.webserverWorkerConnections }}
  WEBSERVER_WORKER_CONNECTIONS: "{{ .Values.webserver.webserverWorkerConnections }}"
  {{- end }}
  BLACKDUCK_RABBIT_SCAOP: "true"
  {{- if .Values.enableApplicationLevelEncryption }}
  SYNOPSYS_CRYPTO_ENABLED: "true"
  {{- end }}
  SYNOPSYS_CRYPTO_PROFILE: "KUBERNETES"
kind: ConfigMap
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: configmap
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
  name: {{ .Release.Name }}-blackduck-config
  namespace: {{ .Release.Namespace }}
