apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: rabbitmq
  name: {{ .Release.Name }}-blackduck-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: amqps
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: streams
    port: 5551
    protocol: TCP
    targetPort: 5551
  # Expose epmd port for rabbitmq CLI tools
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  # Expose rabbit mq admin port for queue-based rate limiting
  - name: management
    port: 15671
    protocol: TCP
    targetPort: 15671
  # Expose Erlang distribution server port for inter-node and CLI tools communication
  - name: rabbitmqctl
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    {{- include "bd.selectorLabelsWithoutVersion" . | nindent 4 }}
    component: rabbitmq
  type: ClusterIP
{{- if and .Values.enablePersistentStorage (not .Values.rabbitmq.persistentVolumeClaimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: pvc
  name: {{ .Release.Name }}-blackduck-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.claimSize }}
  {{- if .Values.rabbitmq.storageClass }}
  storageClassName: {{ .Values.rabbitmq.storageClass }}
  {{- else if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end}}
  {{- if .Values.rabbitmq.volumeName }}
  volumeName: {{ .Values.rabbitmq.volumeName }}
  {{- end -}}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: rabbitmq
  name: {{ .Release.Name }}-blackduck-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "bd.selectorLabelsWithoutVersion" . | nindent 6 }}
      component: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: rabbitmq
      annotations:
        checksum/blackduck-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
        {{- if .Values.rabbitmq.podAnnotations }}
        {{- range $key, $value := .Values.rabbitmq.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      name: {{ .Release.Name }}-blackduck-rabbitmq
    spec:
      {{- if .Values.enableInitContainer }}
      initContainers:
      {{- include "bd.postgresql.up.check.initcontainer" . | indent 6 }}
      {{- end }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - {{ .Release.Name }}-blackduck-rabbitmq
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        {{- if .Values.rabbitmq.registry }}
        image: {{ .Values.rabbitmq.registry }}/rabbitmq:{{ .Values.rabbitmq.imageTag }}
        {{- else }}
        image: {{ .Values.registry }}/rabbitmq:{{ .Values.rabbitmq.imageTag }}
        {{- end}}
        {{- include "customImagePullPolicy" .Values.rabbitmq | nindent 8 }}
        name: rabbitmq
        ports:
        - containerPort: 5671
          protocol: TCP
        - containerPort: 5551
          protocol: TCP
        - containerPort: 4369
          protocol: TCP
        - containerPort: 15671
          protocol: TCP
        - containerPort: 25672
          protocol: TCP
        env:
        - name: RABBITMQ_NODENAME
          value: rabbitmq@{{ .Release.Name }}-blackduck-rabbitmq
        resources:
          {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
        {{- with .Values.rabbitmq.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /opt/blackduck/rabbitmq/security
          name: dir-rabbitmq-security
        - mountPath: /var/lib/rabbitmq
          name: dir-rabbitmq
      dnsPolicy: ClusterFirst
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.rabbitmq.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- if .Values.rabbitmq.podSecurityContext }}
      {{- with .Values.rabbitmq.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: dir-rabbitmq-security
      {{- include "rabbitmqPersistentStorage" . | nindent 6 }}

{{- define "rabbitmqPersistentStorage" -}}
{{- if .Values.enablePersistentStorage -}}
- name: dir-rabbitmq
  persistentVolumeClaim:
    claimName: {{if .Values.rabbitmq.persistentVolumeClaimName}} {{.Values.rabbitmq.persistentVolumeClaimName}} {{else}} {{ .Release.Name }}-blackduck-rabbitmq {{end}}
{{- else -}}
- emptyDir: {}
  name: dir-rabbitmq
{{- end -}}
{{- end -}}
