apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: serviceaccount
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
  name: {{ .Release.Name }}-blackduck-service-account
  namespace: {{ .Release.Namespace }}
