environs:
  SCANNER_CONCURRENCY: "1"
  BLACKDUCK_REDIS_MAXMEMORY: "900mb"
  BLACKDUCK_DEPLOYMENT_BASE_SIZE: "sizes-gen03/120sph.yaml"
  HUB_PG_SHARED_BUFFERS: "5336MB"
  HUB_PG_EFFECTIVE_CACHE_SIZE: "6404MB"
  HUB_PG_AUTOVACUUM_MAX_WORKERS: 4
  HUB_PG_MAINTENANCE_WORK_MEM: "512MB"
  HUB_PG_MAX_CONNECTIONS: 400
  HUB_PG_WORK_MEM: "50MB"

authentication:
  replicas: 1
  hubMaxMemory: "1475m"
  resources:
    limits:
      cpu: "500m"
      memory: "1638Mi"
    requests:
      cpu: "300m"
      memory: "1638Mi"

bomengine:
  replicas: 1
  hubMaxMemory: "4148m"
  resources:
    limits:
      cpu: "1000m"
      memory: "4608Mi"
    requests:
      cpu: "700m"
      memory: "4608Mi"

cfssl:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "260Mi"
    requests:
      cpu: "200m"
      memory: "260Mi"

documentation:
  replicas: 1
  hubMaxMemory: "922m"
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"

jobrunner:
  replicas: 1
  hubMaxMemory: "5807m"
  resources:
    limits:
      cpu: "1500m"
      memory: "6451Mi"
    requests:
      cpu: "1000m"
      memory: "6451Mi"

logstash:
  replicas: 1
  hubMaxMemory: "1567m"
  resources:
    limits:
      cpu: "800m"
      memory: "1741Mi"
    requests:
      cpu: "500m"
      memory: "1741Mi"

matchengine:
  replicas: 2
  hubMaxMemory: "5400m"
  resources:
    limits:
      cpu: "1000m"
      memory: "6000Mi"
    requests:
      cpu: "700m"
      memory: "6000Mi"

postgres:
  replicas: 1
  resources:
    limits:
      cpu: "4000m"
      memory: "16Gi"
    requests:
      cpu: "2000m"
      memory: "16Gi"

postgresUpgrader:
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"

postgresWaiter:
  resources:
    limits:
      cpu: "250m"
      memory: "500Mi"
    requests:
      cpu: "250m"
      memory: "500Mi"

rabbitmq:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "307Mi"

redis:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"

registration:
  replicas: 1
  hubMaxMemory: "1200m"
  resources:
    limits:
      cpu: "300m"
      memory: "1331Mi"
    requests:
      cpu: "200m"
      memory: "1331Mi"

rlservice:
  hubMaxMemory: "5530m"

scan:
  replicas: 1
  hubMaxMemory: "8571m"
  resources:
    limits:
      cpu: "1000m"
      memory: "9523Mi"
    requests:
      cpu: "500m"
      memory: "9523Mi"

storage:
  replicas: 1
  hubMaxMemory: "1024m"
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "700m"
      memory: "2048Mi"

webapp:
  replicas: 1
  hubMaxMemory: "4608m"
  resources:
    limits:
      cpu: "2000m"
      memory: "5120Mi"
    requests:
      cpu: "1000m"
      memory: "5120Mi"

webserver:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
