environs:
  SCANNER_CONCURRENCY: "1"
  BLACKDUCK_REDIS_MAXMEMORY: "900mb"
  BLACKDUCK_DEPLOYMENT_BASE_SIZE: "sizes-gen04/10sph.yaml"
  HUB_PG_SHARED_BUFFERS: "2653MB"
  HUB_PG_EFFECTIVE_CACHE_SIZE: "3185MB"
  HUB_PG_AUTOVACUUM_MAX_WORKERS: 4
  HUB_PG_MAINTENANCE_WORK_MEM: "512MB"
  HUB_PG_MAX_CONNECTIONS: 400
  HUB_PG_WORK_MEM: "50MB"

authentication:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "1229Mi"
    requests:
      cpu: "300m"
      memory: "1229Mi"

bomengine:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "4608Mi"
    requests:
      cpu: "700m"
      memory: "4608Mi"

cfssl:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "260Mi"
    requests:
      cpu: "200m"
      memory: "260Mi"

documentation:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"

jobrunner:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1500m"
      memory: "4710Mi"
    requests:
      cpu: "1000m"
      memory: "4710Mi"

logstash:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "1229Mi"
    requests:
      cpu: "300m"
      memory: "1229Mi"

matchengine:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "5120Mi"
    requests:
      cpu: "700m"
      memory: "5120Mi"

postgres:
  replicas: 1
  resources:
    limits:
      cpu: "2000m"
      memory: "8Gi"
    requests:
      cpu: "1000m"
      memory: "8Gi"

postgresUpgrader:
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"

postgresWaiter:
  resources:
    limits:
      cpu: "250m"
      memory: "500Mi"
    requests:
      cpu: "250m"
      memory: "500Mi"

rabbitmq:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "307Mi"

redis:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"

registration:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "300m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"

scan:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "5120Mi"
    requests:
      cpu: "500m"
      memory: "5120Mi"

storage:
  replicas: 1
  maxRamPercentage: 50
  resources:
    limits:
      cpu: "1000m"
      memory: "2048Mi"
    requests:
      cpu: "700m"
      memory: "2048Mi"

webapp:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "2000m"
      memory: "3584Mi"
    requests:
      cpu: "700m"
      memory: "3584Mi"

webserver:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
