environs:
  SCANNER_CONCURRENCY: "1"
  BLACKDUCK_REDIS_MAXMEMORY: "3687mb"
  BLACKDUCK_DEPLOYMENT_BASE_SIZE: "sizes-gen04/500sph.yaml"
  HUB_PG_SHARED_BUFFERS: "21439MB"
  HUB_PG_EFFECTIVE_CACHE_SIZE: "25727MB"
  HUB_PG_AUTOVACUUM_MAX_WORKERS: 6
  HUB_PG_MAINTENANCE_WORK_MEM: "1024MB"
  HUB_PG_MAX_CONNECTIONS: 500
  HUB_PG_WORK_MEM: "35MB"

authentication:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "2048Mi"
    requests:
      cpu: "300m"
      memory: "1638Mi"

bomengine:
  replicas: 2
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "5120Mi"
    requests:
      cpu: "1000m"
      memory: "5120Mi"

cfssl:
  replicas: 1
  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "260Mi"

documentation:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "1024Mi"

jobrunner:
  replicas: 3
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "8192Mi"
    requests:
      cpu: "1000m"
      memory: "6144Mi"

logstash:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "3072Mi"
    requests:
      cpu: "500m"
      memory: "2048Mi"

matchengine:
  replicas: 4
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "8192Mi"
    requests:
      cpu: "1000m"
      memory: "6144Mi"

postgres:
  replicas: 1
  resources:
    limits:
      cpu: "16000m"
      memory: "64Gi"
    requests:
      cpu: "10000m"
      memory: "64Gi"

postgresUpgrader:
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "4Gi"

postgresWaiter:
  resources:
    limits:
      cpu: "250m"
      memory: "500Mi"
    requests:
      cpu: "250m"
      memory: "500Mi"

rabbitmq:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "300m"
      memory: "512Mi"

redis:
  replicas: 1
  resources:
    limits:
      cpu: "1000m"
      memory: "4096Mi"
    requests:
      cpu: "500m"
      memory: "4096Mi"

registration:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "500m"
      memory: "2048Mi"
    requests:
      cpu: "300m"
      memory: "2048Mi"

scan:
  replicas: 4
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "1000m"
      memory: "10240Mi"
    requests:
      cpu: "700m"
      memory: "10240Mi"

storage:
  replicas: 1
  maxRamPercentage: 75
  resources:
    limits:
      cpu: "1000m"
      memory: "4096Mi"
    requests:
      cpu: "700m"
      memory: "3072Mi"

webapp:
  replicas: 1
  maxRamPercentage: 90
  resources:
    limits:
      cpu: "3000m"
      memory: "6144Mi"
    requests:
      cpu: "2000m"
      memory: "6144Mi"

webserver:
  replicas: 1
  resources:
    limits:
      cpu: "400m"
      memory: "1024Mi"
    requests:
      cpu: "300m"
      memory: "512Mi"
